version: '2'
services:
  common-admin:
    image: common/common-admin
    ports:
    - "8080:8080"
    environment:
    - spring.profiles.active=dev
  common-api:
    image: common/common-api
    ports:
    - "8081:8081"
    environment:
    - spring.profiles.active=dev