#### 建立spring-boot项目
FROM maven:3.8.4-jdk-11 as build

# 作者
MAINTAINER mustang <mustang2247@gmail.com>
# 暴露多个端口
EXPOSE 9080

# 设置项目在docker容器中工作目录
WORKDIR /app

COPY . .
#COPY libs/settings.xml /root/.m2/settings.xml

# 打包应用程序
#RUN mvn clean package -Dmaven.test.skip=true
RUN mvn clean package -P prod -Dmaven.test.skip=true


#### 设置能运行应用程序的最小docker容器
FROM openjdk:11.0.12-jdk-oracle


# VOLUME 指定了临时文件目录为/tmp。
# 其效果是在主机 /var/lib/docker 目录下创建了一个临时文件，并链接到容器的/tmp
VOLUME /tmp
ARG JAR_FILE=/common-admin/target/common-admin.jar
# 注意添加--from=build，不然会报错
COPY --from=build ${JAR_FILE} app.jar
# 将jar包添加到容器中并更名为app.jar

#设置镜像的时区,避免出现8小时的误差
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

EXPOSE 9080

#定义jvm参数变量
ENV JAVA_OPTS=""

# 运行jar包
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar" ]
